services:
  # API Gateway service
  gateway:
    build: .
    container_name: shortlink-gateway
    ports:
      - "8080:8080"
    environment:
      - SHORTLINK_PORT=8080
      - SHORTLINK_ENV=local
      - SHORTLINK_OTEL_EXPORTER_OTLP_ENDPOINT=tempo:4318
      - SHORTLINK_GRPC_SERVER_ADDR=shortlink-core:50051
      - SHORTLINK_USE_GRPC=true
    depends_on:
      - tempo
    networks:
      - shortlink-network
    restart: unless-stopped

  # Observability services
  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    ports:
      - "4318:4318" # OTLP gRPC port
      - "3200:3200" # query api port
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./tempo/tempo.yaml:/etc/tempo.yaml
    networks:
      - shortlink-network

  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - tempo
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - grafana-storage:/var/lib/grafana
    networks:
      - shortlink-network

networks:
  shortlink-network:
    external: true
    name: shortlink-core_shortlink-network

volumes:
  grafana-storage: