apiVersion: 1

datasources:
  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    isDefault: true
    jsonData:
      httpMethod: GET
      serviceMap: true
      nodeGraph: true
      tracesToLogsV2:
        datasourceUid: "loki"
        spanStartTimeShift: 5m
        spanEndTimeShift: 5m
        tags: ["job", "instance", "pod", "namespace"]
        filterByTraceID: true
        filterBySpanID: true
      tracesToMetrics:
        datasourceUid: "prometheus"
        tags: ["service.name"]
