// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/shortlink.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ShortenURLRequest contains the original URL to shorten
type ShortenURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OriginalUrl   string                 `protobuf:"bytes,1,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenURLRequest) Reset() {
	*x = ShortenURLRequest{}
	mi := &file_proto_shortlink_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenURLRequest) ProtoMessage() {}

func (x *ShortenURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortlink_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenURLRequest.ProtoReflect.Descriptor instead.
func (*ShortenURLRequest) Descriptor() ([]byte, []int) {
	return file_proto_shortlink_proto_rawDescGZIP(), []int{0}
}

func (x *ShortenURLRequest) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

// ShortenURLResponse contains the generated short URL ID
type ShortenURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortId       string                 `protobuf:"bytes,1,opt,name=short_id,json=shortId,proto3" json:"short_id,omitempty"`
	ShortUrl      string                 `protobuf:"bytes,2,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"` // Full URL including domain
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenURLResponse) Reset() {
	*x = ShortenURLResponse{}
	mi := &file_proto_shortlink_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenURLResponse) ProtoMessage() {}

func (x *ShortenURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortlink_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenURLResponse.ProtoReflect.Descriptor instead.
func (*ShortenURLResponse) Descriptor() ([]byte, []int) {
	return file_proto_shortlink_proto_rawDescGZIP(), []int{1}
}

func (x *ShortenURLResponse) GetShortId() string {
	if x != nil {
		return x.ShortId
	}
	return ""
}

func (x *ShortenURLResponse) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

// ExpandURLRequest contains the short URL ID to expand
type ExpandURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortId       string                 `protobuf:"bytes,1,opt,name=short_id,json=shortId,proto3" json:"short_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpandURLRequest) Reset() {
	*x = ExpandURLRequest{}
	mi := &file_proto_shortlink_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpandURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpandURLRequest) ProtoMessage() {}

func (x *ExpandURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortlink_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpandURLRequest.ProtoReflect.Descriptor instead.
func (*ExpandURLRequest) Descriptor() ([]byte, []int) {
	return file_proto_shortlink_proto_rawDescGZIP(), []int{2}
}

func (x *ExpandURLRequest) GetShortId() string {
	if x != nil {
		return x.ShortId
	}
	return ""
}

// ExpandURLResponse contains the original URL
type ExpandURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OriginalUrl   string                 `protobuf:"bytes,1,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpandURLResponse) Reset() {
	*x = ExpandURLResponse{}
	mi := &file_proto_shortlink_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpandURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpandURLResponse) ProtoMessage() {}

func (x *ExpandURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortlink_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpandURLResponse.ProtoReflect.Descriptor instead.
func (*ExpandURLResponse) Descriptor() ([]byte, []int) {
	return file_proto_shortlink_proto_rawDescGZIP(), []int{3}
}

func (x *ExpandURLResponse) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

var File_proto_shortlink_proto protoreflect.FileDescriptor

const file_proto_shortlink_proto_rawDesc = "" +
	"\n" +
	"\x15proto/shortlink.proto\x12\tshortlink\"6\n" +
	"\x11ShortenURLRequest\x12!\n" +
	"\foriginal_url\x18\x01 \x01(\tR\voriginalUrl\"L\n" +
	"\x12ShortenURLResponse\x12\x19\n" +
	"\bshort_id\x18\x01 \x01(\tR\ashortId\x12\x1b\n" +
	"\tshort_url\x18\x02 \x01(\tR\bshortUrl\"-\n" +
	"\x10ExpandURLRequest\x12\x19\n" +
	"\bshort_id\x18\x01 \x01(\tR\ashortId\"6\n" +
	"\x11ExpandURLResponse\x12!\n" +
	"\foriginal_url\x18\x01 \x01(\tR\voriginalUrl2\x9f\x01\n" +
	"\n" +
	"URLService\x12I\n" +
	"\n" +
	"ShortenURL\x12\x1c.shortlink.ShortenURLRequest\x1a\x1d.shortlink.ShortenURLResponse\x12F\n" +
	"\tExpandURL\x12\x1b.shortlink.ExpandURLRequest\x1a\x1c.shortlink.ExpandURLResponseB1Z/github.com/yourusername/shortlink-gateway/protob\x06proto3"

var (
	file_proto_shortlink_proto_rawDescOnce sync.Once
	file_proto_shortlink_proto_rawDescData []byte
)

func file_proto_shortlink_proto_rawDescGZIP() []byte {
	file_proto_shortlink_proto_rawDescOnce.Do(func() {
		file_proto_shortlink_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_shortlink_proto_rawDesc), len(file_proto_shortlink_proto_rawDesc)))
	})
	return file_proto_shortlink_proto_rawDescData
}

var file_proto_shortlink_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_shortlink_proto_goTypes = []any{
	(*ShortenURLRequest)(nil),  // 0: shortlink.ShortenURLRequest
	(*ShortenURLResponse)(nil), // 1: shortlink.ShortenURLResponse
	(*ExpandURLRequest)(nil),   // 2: shortlink.ExpandURLRequest
	(*ExpandURLResponse)(nil),  // 3: shortlink.ExpandURLResponse
}
var file_proto_shortlink_proto_depIdxs = []int32{
	0, // 0: shortlink.URLService.ShortenURL:input_type -> shortlink.ShortenURLRequest
	2, // 1: shortlink.URLService.ExpandURL:input_type -> shortlink.ExpandURLRequest
	1, // 2: shortlink.URLService.ShortenURL:output_type -> shortlink.ShortenURLResponse
	3, // 3: shortlink.URLService.ExpandURL:output_type -> shortlink.ExpandURLResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_shortlink_proto_init() }
func file_proto_shortlink_proto_init() {
	if File_proto_shortlink_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_shortlink_proto_rawDesc), len(file_proto_shortlink_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_shortlink_proto_goTypes,
		DependencyIndexes: file_proto_shortlink_proto_depIdxs,
		MessageInfos:      file_proto_shortlink_proto_msgTypes,
	}.Build()
	File_proto_shortlink_proto = out.File
	file_proto_shortlink_proto_goTypes = nil
	file_proto_shortlink_proto_depIdxs = nil
}
